python -m pip install "pymongo[srv]==3.12"

In [3]:
import pandas as pd

In [7]:
df = pd.read_csv("Graduate.csv")
df.head()

,GRE_Score,TOEFL_Score,IELTS_Score,CGPA,University_Rating,SOP,LOR,Research,Publications,Work_Experience_Months,Internship,Leadership_Score,Awards_Count,Country,Target_Program,Graduation_Year,Scholarship_Awarded
0,295.0,96.0,7.5,2.93,2,4.9,1.7,0,1,8,No,5,0,Nepal,EMJM Cyber,2024,No
1,340.0,119.0,9.0,3.76,3,4.1,1.7,0,1,31,Yes,4,0,Pakistan,EMJM Cyber,2025,No
2,336.0,96.0,7.5,3.12,1,3.2,1.8,1,2,29,Yes,4,1,Bangladesh,EMJM Cyber,2022,No
3,337.0,108.0,8.0,2.11,4,3.4,1.3,0,0,35,Yes,3,0,Bangladesh,EMJM DS,2025,No
4,323.0,98.0,7.5,3.40,1,1.1,1.3,0,1,16,Yes,2,0,India,EMJM DS,2025,No

In [8]:
df.shape

(1000, 17)

In [9]:
df.columns

Index(['GRE_Score', 'TOEFL_Score', 'IELTS_Score', 'CGPA', 'University_Rating',
       'SOP', 'LOR', 'Research', 'Publications', 'Work_Experience_Months',
       'Internship', 'Leadership_Score', 'Awards_Count', 'Country',
       'Target_Program', 'Graduation_Year', 'Scholarship_Awarded'],
      dtype='object')

In [10]:
data = df.to_dict(orient='records')
data

[{'GRE_Score': 295.0,
  'TOEFL_Score': 96.0,
  'IELTS_Score': 7.5,
  'CGPA': 2.93,
  'University_Rating': 2,
  'SOP': 4.9,
  'LOR': 1.7,
  'Research': 0,
  'Publications': 1,
  'Work_Experience_Months': 8,
  'Internship': 'No',
  'Leadership_Score': 5,
  'Awards_Count': 0,
  'Country': 'Nepal',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 340.0,
  'TOEFL_Score': 119.0,
  'IELTS_Score': 9.0,
  'CGPA': 3.76,
  'University_Rating': 3,
  'SOP': 4.1,
  'LOR': 1.7,
  'Research': 0,
  'Publications': 1,
  'Work_Experience_Months': 31,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 336.0,
  'TOEFL_Score': 96.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.12,
  'University_Rating': 1,
  'SOP': 3.2,
  'LOR': 1.8,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 29,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 1,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2022,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 337.0,
  'TOEFL_Score': 108.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.11,
  'University_Rating': 4,
  'SOP': 3.4,
  'LOR': 1.3,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 35,
  'Internship': 'Yes',
  'Leadership_Score': 3,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 323.0,
  'TOEFL_Score': 98.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.4,
  'University_Rating': 1,
  'SOP': 1.1,
  'LOR': 1.3,
  'Research': 0,
  'Publications': 1,
  'Work_Experience_Months': 16,
  'Internship': 'Yes',
  'Leadership_Score': 2,
  'Awards_Count': 0,
  'Country': 'India',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 302.0,
  'TOEFL_Score': 110.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.89,
  'University_Rating': 2,
  'SOP': 4.3,
  'LOR': 1.7,
  'Research': 0,
  'Publications': 2,
  'Work_Experience_Months': 6,
  'Internship': 'No',
  'Leadership_Score': 5,
  'Awards_Count': 1,
  'Country': 'Nepal',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 335.0,
  'TOEFL_Score': 112.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.16,
  'University_Rating': 3,
  'SOP': 1.5,
  'LOR': 3.0,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 28,
  'Internship': 'Yes',
  'Leadership_Score': 3,
  'Awards_Count': 0,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 332.0,
  'TOEFL_Score': 115.0,
  'IELTS_Score': 8.5,
  'CGPA': 2.21,
  'University_Rating': 2,
  'SOP': 2.2,
  'LOR': 1.3,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 27,
  'Internship': 'Yes',
  'Leadership_Score': 2,
  'Awards_Count': 0,
  'Country': 'Nepal',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 330.0,
  'TOEFL_Score': 110.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.17,
  'University_Rating': 2,
  'SOP': 2.9,
  'LOR': 4.7,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 20,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 0,
  'Country': 'India',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 296.0,
  'TOEFL_Score': 107.0,
  'IELTS_Score': 8.0,
  'CGPA': 3.42,
  'University_Rating': 2,
  'SOP': 1.5,
  'LOR': 3.2,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 3,
  'Internship': 'No',
  'Leadership_Score': 3,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 308.0,
  'TOEFL_Score': 120.0,
  'IELTS_Score': 9.0,
  'CGPA': 2.49,
  'University_Rating': 5,
  'SOP': 1.3,
  'LOR': 4.6,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 9,
  'Internship': 'No',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 317.0,
  'TOEFL_Score': 96.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.22,
  'University_Rating': 1,
  'SOP': 1.9,
  'LOR': 2.4,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 25,
  'Internship': 'Yes',
  'Leadership_Score': 3,
  'Awards_Count': 1,
  'Country': 'India',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 301.0,
  'TOEFL_Score': 118.0,
  'IELTS_Score': 9.0,
  'CGPA': 3.49,
  'University_Rating': 4,
  'SOP': 5.0,
  'LOR': 2.8,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 17,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 0,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 327.0,
  'TOEFL_Score': 100.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.58,
  'University_Rating': 3,
  'SOP': 4.3,
  'LOR': 3.6,
  'Research': 1,
  'Publications': 3,
  'Work_Experience_Months': 24,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 1,
  'Country': 'Nepal',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 325.0,
  'TOEFL_Score': 99.0,
  'IELTS_Score': 7.5,
  'CGPA': 2.05,
  'University_Rating': 3,
  'SOP': 1.8,
  'LOR': 3.9,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 29,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'India',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 331.0,
  'TOEFL_Score': 116.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.31,
  'University_Rating': 2,
  'SOP': 3.0,
  'LOR': 3.7,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 32,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 1,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 305.0,
  'TOEFL_Score': 107.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.13,
  'University_Rating': 4,
  'SOP': 4.6,
  'LOR': 3.3,
  'Research': 1,
  'Publications': 0,
  'Work_Experience_Months': 7,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 0,
  'Country': 'Nepal',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 323.0,
  'TOEFL_Score': 111.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.39,
  'University_Rating': 5,
  'SOP': 4.4,
  'LOR': 2.6,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 22,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 0,
  'Country': 'Nepal',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 315.0,
  'TOEFL_Score': 96.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.85,
  'University_Rating': 1,
  'SOP': 2.7,
  'LOR': 3.4,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 24,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 1,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 327.0,
  'TOEFL_Score': 101.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.36,
  'University_Rating': 2,
  'SOP': 4.4,
  'LOR': 1.6,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 18,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 1,
  'Country': 'Nepal',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 308.0,
  'TOEFL_Score': 103.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.75,
  'University_Rating': 3,
  'SOP': 3.6,
  'LOR': 2.6,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 15,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 0,
  'Country': 'India',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 338.0,
  'TOEFL_Score': 99.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.88,
  'University_Rating': 2,
  'SOP': 2.2,
  'LOR': 2.7,
  'Research': 0,
  'Publications': 2,
  'Work_Experience_Months': 36,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 1,
  'Country': 'India',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 313.0,
  'TOEFL_Score': 117.0,
  'IELTS_Score': 8.5,
  'CGPA': 2.19,
  'University_Rating': 4,
  'SOP': 3.5,
  'LOR': 2.2,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 23,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 296.0,
  'TOEFL_Score': 120.0,
  'IELTS_Score': 9.0,
  'CGPA': 2.89,
  'University_Rating': 5,
  'SOP': 2.1,
  'LOR': 3.7,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 9,
  'Internship': 'No',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 316.0,
  'TOEFL_Score': 107.0,
  'IELTS_Score': 8.0,
  'CGPA': 3.2,
  'University_Rating': 4,
  'SOP': 2.6,
  'LOR': 2.9,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 25,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Nepal',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 324.0,
  'TOEFL_Score': 100.0,
  'IELTS_Score': 7.5,
  'CGPA': 4.0,
  'University_Rating': 1,
  'SOP': 3.0,
  'LOR': 4.6,
  'Research': 0,
  'Publications': 3,
  'Work_Experience_Months': 29,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 1,
  'Country': 'India',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 300.0,
  'TOEFL_Score': 112.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.21,
  'University_Rating': 2,
  'SOP': 1.6,
  'LOR': 4.5,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 11,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 0,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 337.0,
  'TOEFL_Score': 107.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.23,
  'University_Rating': 2,
  'SOP': 2.2,
  'LOR': 4.1,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 35,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 337.0,
  'TOEFL_Score': 98.0,
  'IELTS_Score': 7.5,
  'CGPA': 2.62,
  'University_Rating': 4,
  'SOP': 2.6,
  'LOR': 2.6,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 29,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 1,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 328.0,
  'TOEFL_Score': 99.0,
  'IELTS_Score': 7.5,
  'CGPA': 2.65,
  'University_Rating': 4,
  'SOP': 3.9,
  'LOR': 4.5,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 19,
  'Internship': 'Yes',
  'Leadership_Score': 7,
  'Awards_Count': 1,
  'Country': 'India',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 339.0,
  'TOEFL_Score': 104.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.75,
  'University_Rating': 5,
  'SOP': 4.8,
  'LOR': 4.7,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 24,
  'Internship': 'Yes',
  'Leadership_Score': 7,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 337.0,
  'TOEFL_Score': 116.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.68,
  'University_Rating': 2,
  'SOP': 2.0,
  'LOR': 3.7,
  'Research': 0,
  'Publications': 1,
  'Work_Experience_Months': 35,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 325.0,
  'TOEFL_Score': 101.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.16,
  'University_Rating': 5,
  'SOP': 2.0,
  'LOR': 1.4,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 23,
  'Internship': 'Yes',
  'Leadership_Score': 2,
  'Awards_Count': 1,
  'Country': 'Nepal',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 327.0,
  'TOEFL_Score': 103.0,
  'IELTS_Score': 8.0,
  'CGPA': 3.08,
  'University_Rating': 3,
  'SOP': 3.4,
  'LOR': 2.4,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 18,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 306.0,
  'TOEFL_Score': 108.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.74,
  'University_Rating': 4,
  'SOP': 1.1,
  'LOR': 2.5,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 14,
  'Internship': 'Yes',
  'Leadership_Score': 3,
  'Awards_Count': 0,
  'Country': 'Nepal',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 337.0,
  'TOEFL_Score': 93.0,
  'IELTS_Score': 7.0,
  'CGPA': 2.77,
  'University_Rating': 2,
  'SOP': 4.6,
  'LOR': 3.0,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 23,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 0,
  'Country': 'Nepal',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2022,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 333.0,
  'TOEFL_Score': 100.0,
  'IELTS_Score': 7.5,
  'CGPA': 2.61,
  'University_Rating': 5,
  'SOP': 3.6,
  'LOR': 3.7,
  'Research': 1,
  'Publications': 1,
  'Work_Experience_Months': 27,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 0,
  'Country': 'India',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 340.0,
  'TOEFL_Score': 102.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.84,
  'University_Rating': 1,
  'SOP': 3.3,
  'LOR': 2.6,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 31,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 1,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 323.0,
  'TOEFL_Score': 114.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.32,
  'University_Rating': 5,
  'SOP': 1.7,
  'LOR': 3.4,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 16,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 304.0,
  'TOEFL_Score': 98.0,
  'IELTS_Score': 7.5,
  'CGPA': 2.13,
  'University_Rating': 4,
  'SOP': 2.6,
  'LOR': 3.4,
  'Research': 1,
  'Publications': 0,
  'Work_Experience_Months': 19,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 0,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 327.0,
  'TOEFL_Score': 93.0,
  'IELTS_Score': 7.0,
  'CGPA': 3.8,
  'University_Rating': 5,
  'SOP': 3.3,
  'LOR': 2.2,
  'Research': 0,
  'Publications': 2,
  'Work_Experience_Months': 30,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 1,
  'Country': 'India',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2022,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 296.0,
  'TOEFL_Score': 109.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.42,
  'University_Rating': 1,
  'SOP': 1.1,
  'LOR': 4.5,
  'Research': 1,
  'Publications': 0,
  'Work_Experience_Months': 9,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 322.0,
  'TOEFL_Score': 97.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.56,
  'University_Rating': 1,
  'SOP': 1.3,
  'LOR': 4.0,
  'Research': 1,
  'Publications': 3,
  'Work_Experience_Months': 22,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 1,
  'Country': 'India',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2022,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 305.0,
  'TOEFL_Score': 101.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.3,
  'University_Rating': 2,
  'SOP': 3.3,
  'LOR': 1.2,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 13,
  'Internship': 'Yes',
  'Leadership_Score': 3,
  'Awards_Count': 1,
  'Country': 'Nepal',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 325.0,
  'TOEFL_Score': 115.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.39,
  'University_Rating': 4,
  'SOP': 2.9,
  'LOR': 4.5,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 23,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 0,
  'Country': 'India',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 300.0,
  'TOEFL_Score': 105.0,
  'IELTS_Score': 8.0,
  'CGPA': 2.19,
  'University_Rating': 2,
  'SOP': 2.8,
  'LOR': 1.1,
  'Research': 1,
  'Publications': 0,
  'Work_Experience_Months': 17,
  'Internship': 'Yes',
  'Leadership_Score': 3,
  'Awards_Count': 0,
  'Country': 'Nepal',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2022,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 311.0,
  'TOEFL_Score': 113.0,
  'IELTS_Score': 8.5,
  'CGPA': 2.23,
  'University_Rating': 1,
  'SOP': 3.0,
  'LOR': 2.0,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 10,
  'Internship': 'No',
  'Leadership_Score': 4,
  'Awards_Count': 0,
  'Country': 'India',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2024,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 324.0,
  'TOEFL_Score': 96.0,
  'IELTS_Score': 7.5,
  'CGPA': 3.3,
  'University_Rating': 5,
  'SOP': 4.8,
  'LOR': 1.9,
  'Research': 0,
  'Publications': 0,
  'Work_Experience_Months': 23,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 0,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM Cyber',
  'Graduation_Year': 2025,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 297.0,
  'TOEFL_Score': 107.0,
  'IELTS_Score': 8.0,
  'CGPA': 3.84,
  'University_Rating': 2,
  'SOP': 3.0,
  'LOR': 4.3,
  'Research': 0,
  'Publications': 2,
  'Work_Experience_Months': 15,
  'Internship': 'Yes',
  'Leadership_Score': 6,
  'Awards_Count': 1,
  'Country': 'India',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2022,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 319.0,
  'TOEFL_Score': 107.0,
  'IELTS_Score': 8.0,
  'CGPA': 3.4,
  'University_Rating': 3,
  'SOP': 4.9,
  'LOR': 1.5,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 20,
  'Internship': 'Yes',
  'Leadership_Score': 5,
  'Awards_Count': 1,
  'Country': 'Bangladesh',
  'Target_Program': 'EMJM AI',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'Yes'},
 {'GRE_Score': 310.0,
  'TOEFL_Score': 111.0,
  'IELTS_Score': 8.5,
  'CGPA': 3.14,
  'University_Rating': 2,
  'SOP': 1.4,
  'LOR': 4.3,
  'Research': 1,
  'Publications': 2,
  'Work_Experience_Months': 16,
  'Internship': 'Yes',
  'Leadership_Score': 4,
  'Awards_Count': 1,
  'Country': 'Pakistan',
  'Target_Program': 'EMJM DS',
  'Graduation_Year': 2023,
  'Scholarship_Awarded': 'No'},
 {'GRE_Score': 300.0,

In [11]:
DD_NAME = "scholarship"
COLLECTION_NAME = "scholarship_data"
CONNECTION_URL = "mongodb+srv://helloshakibx_db_user:NsqPrMAR5FfIMmo8@cluster0.qt4bcek.mongodb.net"

In [16]:
import pymongo

client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DD_NAME]
collection = data_base[COLLECTION_NAME]

SSLError: [ASN1: NOT_ENOUGH_DATA] not enough data (_ssl.c:4194)

In [19]:
import pymongo
import certifi

# certifi ব্যবহার করে SSL এরর ফিক্স করা হয়েছে
client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())

# ডাটাবেস এবং কালেকশন তৈরি
data_base = client[DD_NAME]
collection = data_base[COLLECTION_NAME]

# ডেটাবেসে ডেটা ইনসার্ট করা
rec = collection.insert_many(data)

print(f"Total {len(rec.inserted_ids)} records inserted successfully!")

Total 1000 records inserted successfully!

In [20]:
records = collection.find()
records

In [21]:
for i, j in enumerate(records):
    print(f"{i} : {j}")

0 : {'_id': ObjectId('6a5c93656eed02b82b98192c'), 'GRE_Score': 295.0, 'TOEFL_Score': 96.0, 'IELTS_Score': 7.5, 'CGPA': 2.93, 'University_Rating': 2, 'SOP': 4.9, 'LOR': 1.7, 'Research': 0, 'Publications': 1, 'Work_Experience_Months': 8, 'Internship': 'No', 'Leadership_Score': 5, 'Awards_Count': 0, 'Country': 'Nepal', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
1 : {'_id': ObjectId('6a5c93656eed02b82b98192d'), 'GRE_Score': 340.0, 'TOEFL_Score': 119.0, 'IELTS_Score': 9.0, 'CGPA': 3.76, 'University_Rating': 3, 'SOP': 4.1, 'LOR': 1.7, 'Research': 0, 'Publications': 1, 'Work_Experience_Months': 31, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Pakistan', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
2 : {'_id': ObjectId('6a5c93656eed02b82b98192e'), 'GRE_Score': 336.0, 'TOEFL_Score': 96.0, 'IELTS_Score': 7.5, 'CGPA': 3.12, 'University_Rating': 1, 'SOP': 3.2, 'LOR': 1.8, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 29, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 1, 'Country': 'Bangladesh', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2022, 'Scholarship_Awarded': 'No'}
3 : {'_id': ObjectId('6a5c93656eed02b82b98192f'), 'GRE_Score': 337.0, 'TOEFL_Score': 108.0, 'IELTS_Score': 8.0, 'CGPA': 2.11, 'University_Rating': 4, 'SOP': 3.4, 'LOR': 1.3, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 35, 'Internship': 'Yes', 'Leadership_Score': 3, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
4 : {'_id': ObjectId('6a5c93656eed02b82b981930'), 'GRE_Score': 323.0, 'TOEFL_Score': 98.0, 'IELTS_Score': 7.5, 'CGPA': 3.4, 'University_Rating': 1, 'SOP': 1.1, 'LOR': 1.3, 'Research': 0, 'Publications': 1, 'Work_Experience_Months': 16, 'Internship': 'Yes', 'Leadership_Score': 2, 'Awards_Count': 0, 'Country': 'India', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
5 : {'_id': ObjectId('6a5c93656eed02b82b981931'), 'GRE_Score': 302.0, 'TOEFL_Score': 110.0, 'IELTS_Score': 8.5, 'CGPA': 3.89, 'University_Rating': 2, 'SOP': 4.3, 'LOR': 1.7, 'Research': 0, 'Publications': 2, 'Work_Experience_Months': 6, 'Internship': 'No', 'Leadership_Score': 5, 'Awards_Count': 1, 'Country': 'Nepal', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
6 : {'_id': ObjectId('6a5c93656eed02b82b981932'), 'GRE_Score': 335.0, 'TOEFL_Score': 112.0, 'IELTS_Score': 8.5, 'CGPA': 3.16, 'University_Rating': 3, 'SOP': 1.5, 'LOR': 3.0, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 28, 'Internship': 'Yes', 'Leadership_Score': 3, 'Awards_Count': 0, 'Country': 'Pakistan', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
7 : {'_id': ObjectId('6a5c93656eed02b82b981933'), 'GRE_Score': 332.0, 'TOEFL_Score': 115.0, 'IELTS_Score': 8.5, 'CGPA': 2.21, 'University_Rating': 2, 'SOP': 2.2, 'LOR': 1.3, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 27, 'Internship': 'Yes', 'Leadership_Score': 2, 'Awards_Count': 0, 'Country': 'Nepal', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
8 : {'_id': ObjectId('6a5c93656eed02b82b981934'), 'GRE_Score': 330.0, 'TOEFL_Score': 110.0, 'IELTS_Score': 8.5, 'CGPA': 3.17, 'University_Rating': 2, 'SOP': 2.9, 'LOR': 4.7, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 20, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 0, 'Country': 'India', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
9 : {'_id': ObjectId('6a5c93656eed02b82b981935'), 'GRE_Score': 296.0, 'TOEFL_Score': 107.0, 'IELTS_Score': 8.0, 'CGPA': 3.42, 'University_Rating': 2, 'SOP': 1.5, 'LOR': 3.2, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 3, 'Internship': 'No', 'Leadership_Score': 3, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
10 : {'_id': ObjectId('6a5c93656eed02b82b981936'), 'GRE_Score': 308.0, 'TOEFL_Score': 120.0, 'IELTS_Score': 9.0, 'CGPA': 2.49, 'University_Rating': 5, 'SOP': 1.3, 'LOR': 4.6, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 9, 'Internship': 'No', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
11 : {'_id': ObjectId('6a5c93656eed02b82b981937'), 'GRE_Score': 317.0, 'TOEFL_Score': 96.0, 'IELTS_Score': 7.5, 'CGPA': 3.22, 'University_Rating': 1, 'SOP': 1.9, 'LOR': 2.4, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 25, 'Internship': 'Yes', 'Leadership_Score': 3, 'Awards_Count': 1, 'Country': 'India', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
12 : {'_id': ObjectId('6a5c93656eed02b82b981938'), 'GRE_Score': 301.0, 'TOEFL_Score': 118.0, 'IELTS_Score': 9.0, 'CGPA': 3.49, 'University_Rating': 4, 'SOP': 5.0, 'LOR': 2.8, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 17, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 0, 'Country': 'Pakistan', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'Yes'}
13 : {'_id': ObjectId('6a5c93656eed02b82b981939'), 'GRE_Score': 327.0, 'TOEFL_Score': 100.0, 'IELTS_Score': 7.5, 'CGPA': 3.58, 'University_Rating': 3, 'SOP': 4.3, 'LOR': 3.6, 'Research': 1, 'Publications': 3, 'Work_Experience_Months': 24, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 1, 'Country': 'Nepal', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'Yes'}
14 : {'_id': ObjectId('6a5c93656eed02b82b98193a'), 'GRE_Score': 325.0, 'TOEFL_Score': 99.0, 'IELTS_Score': 7.5, 'CGPA': 2.05, 'University_Rating': 3, 'SOP': 1.8, 'LOR': 3.9, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 29, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'India', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
15 : {'_id': ObjectId('6a5c93656eed02b82b98193b'), 'GRE_Score': 331.0, 'TOEFL_Score': 116.0, 'IELTS_Score': 8.5, 'CGPA': 3.31, 'University_Rating': 2, 'SOP': 3.0, 'LOR': 3.7, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 32, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 1, 'Country': 'Pakistan', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'Yes'}
16 : {'_id': ObjectId('6a5c93656eed02b82b98193c'), 'GRE_Score': 305.0, 'TOEFL_Score': 107.0, 'IELTS_Score': 8.0, 'CGPA': 2.13, 'University_Rating': 4, 'SOP': 4.6, 'LOR': 3.3, 'Research': 1, 'Publications': 0, 'Work_Experience_Months': 7, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 0, 'Country': 'Nepal', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
17 : {'_id': ObjectId('6a5c93656eed02b82b98193d'), 'GRE_Score': 323.0, 'TOEFL_Score': 111.0, 'IELTS_Score': 8.5, 'CGPA': 3.39, 'University_Rating': 5, 'SOP': 4.4, 'LOR': 2.6, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 22, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 0, 'Country': 'Nepal', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
18 : {'_id': ObjectId('6a5c93656eed02b82b98193e'), 'GRE_Score': 315.0, 'TOEFL_Score': 96.0, 'IELTS_Score': 7.5, 'CGPA': 3.85, 'University_Rating': 1, 'SOP': 2.7, 'LOR': 3.4, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 24, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 1, 'Country': 'Bangladesh', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
19 : {'_id': ObjectId('6a5c93656eed02b82b98193f'), 'GRE_Score': 327.0, 'TOEFL_Score': 101.0, 'IELTS_Score': 7.5, 'CGPA': 3.36, 'University_Rating': 2, 'SOP': 4.4, 'LOR': 1.6, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 18, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 1, 'Country': 'Nepal', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'Yes'}
20 : {'_id': ObjectId('6a5c93656eed02b82b981940'), 'GRE_Score': 308.0, 'TOEFL_Score': 103.0, 'IELTS_Score': 8.0, 'CGPA': 2.75, 'University_Rating': 3, 'SOP': 3.6, 'LOR': 2.6, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 15, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 0, 'Country': 'India', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
21 : {'_id': ObjectId('6a5c93656eed02b82b981941'), 'GRE_Score': 338.0, 'TOEFL_Score': 99.0, 'IELTS_Score': 7.5, 'CGPA': 3.88, 'University_Rating': 2, 'SOP': 2.2, 'LOR': 2.7, 'Research': 0, 'Publications': 2, 'Work_Experience_Months': 36, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 1, 'Country': 'India', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
22 : {'_id': ObjectId('6a5c93656eed02b82b981942'), 'GRE_Score': 313.0, 'TOEFL_Score': 117.0, 'IELTS_Score': 8.5, 'CGPA': 2.19, 'University_Rating': 4, 'SOP': 3.5, 'LOR': 2.2, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 23, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Pakistan', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
23 : {'_id': ObjectId('6a5c93656eed02b82b981943'), 'GRE_Score': 296.0, 'TOEFL_Score': 120.0, 'IELTS_Score': 9.0, 'CGPA': 2.89, 'University_Rating': 5, 'SOP': 2.1, 'LOR': 3.7, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 9, 'Internship': 'No', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Pakistan', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
24 : {'_id': ObjectId('6a5c93656eed02b82b981944'), 'GRE_Score': 316.0, 'TOEFL_Score': 107.0, 'IELTS_Score': 8.0, 'CGPA': 3.2, 'University_Rating': 4, 'SOP': 2.6, 'LOR': 2.9, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 25, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Nepal', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
25 : {'_id': ObjectId('6a5c93656eed02b82b981945'), 'GRE_Score': 324.0, 'TOEFL_Score': 100.0, 'IELTS_Score': 7.5, 'CGPA': 4.0, 'University_Rating': 1, 'SOP': 3.0, 'LOR': 4.6, 'Research': 0, 'Publications': 3, 'Work_Experience_Months': 29, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 1, 'Country': 'India', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
26 : {'_id': ObjectId('6a5c93656eed02b82b981946'), 'GRE_Score': 300.0, 'TOEFL_Score': 112.0, 'IELTS_Score': 8.5, 'CGPA': 3.21, 'University_Rating': 2, 'SOP': 1.6, 'LOR': 4.5, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 11, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 0, 'Country': 'Pakistan', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'Yes'}
27 : {'_id': ObjectId('6a5c93656eed02b82b981947'), 'GRE_Score': 337.0, 'TOEFL_Score': 107.0, 'IELTS_Score': 8.0, 'CGPA': 2.23, 'University_Rating': 2, 'SOP': 2.2, 'LOR': 4.1, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 35, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
28 : {'_id': ObjectId('6a5c93656eed02b82b981948'), 'GRE_Score': 337.0, 'TOEFL_Score': 98.0, 'IELTS_Score': 7.5, 'CGPA': 2.62, 'University_Rating': 4, 'SOP': 2.6, 'LOR': 2.6, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 29, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 1, 'Country': 'Pakistan', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
29 : {'_id': ObjectId('6a5c93656eed02b82b981949'), 'GRE_Score': 328.0, 'TOEFL_Score': 99.0, 'IELTS_Score': 7.5, 'CGPA': 2.65, 'University_Rating': 4, 'SOP': 3.9, 'LOR': 4.5, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 19, 'Internship': 'Yes', 'Leadership_Score': 7, 'Awards_Count': 1, 'Country': 'India', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'Yes'}
30 : {'_id': ObjectId('6a5c93656eed02b82b98194a'), 'GRE_Score': 339.0, 'TOEFL_Score': 104.0, 'IELTS_Score': 8.0, 'CGPA': 2.75, 'University_Rating': 5, 'SOP': 4.8, 'LOR': 4.7, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 24, 'Internship': 'Yes', 'Leadership_Score': 7, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
31 : {'_id': ObjectId('6a5c93656eed02b82b98194b'), 'GRE_Score': 337.0, 'TOEFL_Score': 116.0, 'IELTS_Score': 8.5, 'CGPA': 3.68, 'University_Rating': 2, 'SOP': 2.0, 'LOR': 3.7, 'Research': 0, 'Publications': 1, 'Work_Experience_Months': 35, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
32 : {'_id': ObjectId('6a5c93656eed02b82b98194c'), 'GRE_Score': 325.0, 'TOEFL_Score': 101.0, 'IELTS_Score': 7.5, 'CGPA': 3.16, 'University_Rating': 5, 'SOP': 2.0, 'LOR': 1.4, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 23, 'Internship': 'Yes', 'Leadership_Score': 2, 'Awards_Count': 1, 'Country': 'Nepal', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'Yes'}
33 : {'_id': ObjectId('6a5c93656eed02b82b98194d'), 'GRE_Score': 327.0, 'TOEFL_Score': 103.0, 'IELTS_Score': 8.0, 'CGPA': 3.08, 'University_Rating': 3, 'SOP': 3.4, 'LOR': 2.4, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 18, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Pakistan', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
34 : {'_id': ObjectId('6a5c93656eed02b82b98194e'), 'GRE_Score': 306.0, 'TOEFL_Score': 108.0, 'IELTS_Score': 8.0, 'CGPA': 2.74, 'University_Rating': 4, 'SOP': 1.1, 'LOR': 2.5, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 14, 'Internship': 'Yes', 'Leadership_Score': 3, 'Awards_Count': 0, 'Country': 'Nepal', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
35 : {'_id': ObjectId('6a5c93656eed02b82b98194f'), 'GRE_Score': 337.0, 'TOEFL_Score': 93.0, 'IELTS_Score': 7.0, 'CGPA': 2.77, 'University_Rating': 2, 'SOP': 4.6, 'LOR': 3.0, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 23, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 0, 'Country': 'Nepal', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2022, 'Scholarship_Awarded': 'No'}
36 : {'_id': ObjectId('6a5c93656eed02b82b981950'), 'GRE_Score': 333.0, 'TOEFL_Score': 100.0, 'IELTS_Score': 7.5, 'CGPA': 2.61, 'University_Rating': 5, 'SOP': 3.6, 'LOR': 3.7, 'Research': 1, 'Publications': 1, 'Work_Experience_Months': 27, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 0, 'Country': 'India', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'Yes'}
37 : {'_id': ObjectId('6a5c93656eed02b82b981951'), 'GRE_Score': 340.0, 'TOEFL_Score': 102.0, 'IELTS_Score': 8.0, 'CGPA': 2.84, 'University_Rating': 1, 'SOP': 3.3, 'LOR': 2.6, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 31, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 1, 'Country': 'Bangladesh', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
38 : {'_id': ObjectId('6a5c93656eed02b82b981952'), 'GRE_Score': 323.0, 'TOEFL_Score': 114.0, 'IELTS_Score': 8.5, 'CGPA': 3.32, 'University_Rating': 5, 'SOP': 1.7, 'LOR': 3.4, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 16, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
39 : {'_id': ObjectId('6a5c93656eed02b82b981953'), 'GRE_Score': 304.0, 'TOEFL_Score': 98.0, 'IELTS_Score': 7.5, 'CGPA': 2.13, 'University_Rating': 4, 'SOP': 2.6, 'LOR': 3.4, 'Research': 1, 'Publications': 0, 'Work_Experience_Months': 19, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 0, 'Country': 'Pakistan', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
40 : {'_id': ObjectId('6a5c93656eed02b82b981954'), 'GRE_Score': 327.0, 'TOEFL_Score': 93.0, 'IELTS_Score': 7.0, 'CGPA': 3.8, 'University_Rating': 5, 'SOP': 3.3, 'LOR': 2.2, 'Research': 0, 'Publications': 2, 'Work_Experience_Months': 30, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 1, 'Country': 'India', 'Target_Program': 'EMJM AI', 'Graduation_Year': 2022, 'Scholarship_Awarded': 'No'}
41 : {'_id': ObjectId('6a5c93656eed02b82b981955'), 'GRE_Score': 296.0, 'TOEFL_Score': 109.0, 'IELTS_Score': 8.0, 'CGPA': 2.42, 'University_Rating': 1, 'SOP': 1.1, 'LOR': 4.5, 'Research': 1, 'Publications': 0, 'Work_Experience_Months': 9, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2023, 'Scholarship_Awarded': 'No'}
42 : {'_id': ObjectId('6a5c93656eed02b82b981956'), 'GRE_Score': 322.0, 'TOEFL_Score': 97.0, 'IELTS_Score': 7.5, 'CGPA': 3.56, 'University_Rating': 1, 'SOP': 1.3, 'LOR': 4.0, 'Research': 1, 'Publications': 3, 'Work_Experience_Months': 22, 'Internship': 'Yes', 'Leadership_Score': 4, 'Awards_Count': 1, 'Country': 'India', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2022, 'Scholarship_Awarded': 'No'}
43 : {'_id': ObjectId('6a5c93656eed02b82b981957'), 'GRE_Score': 305.0, 'TOEFL_Score': 101.0, 'IELTS_Score': 7.5, 'CGPA': 3.3, 'University_Rating': 2, 'SOP': 3.3, 'LOR': 1.2, 'Research': 1, 'Publications': 2, 'Work_Experience_Months': 13, 'Internship': 'Yes', 'Leadership_Score': 3, 'Awards_Count': 1, 'Country': 'Nepal', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
44 : {'_id': ObjectId('6a5c93656eed02b82b981958'), 'GRE_Score': 325.0, 'TOEFL_Score': 115.0, 'IELTS_Score': 8.5, 'CGPA': 3.39, 'University_Rating': 4, 'SOP': 2.9, 'LOR': 4.5, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 23, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 0, 'Country': 'India', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
45 : {'_id': ObjectId('6a5c93656eed02b82b981959'), 'GRE_Score': 300.0, 'TOEFL_Score': 105.0, 'IELTS_Score': 8.0, 'CGPA': 2.19, 'University_Rating': 2, 'SOP': 2.8, 'LOR': 1.1, 'Research': 1, 'Publications': 0, 'Work_Experience_Months': 17, 'Internship': 'Yes', 'Leadership_Score': 3, 'Awards_Count': 0, 'Country': 'Nepal', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2022, 'Scholarship_Awarded': 'No'}
46 : {'_id': ObjectId('6a5c93656eed02b82b98195a'), 'GRE_Score': 311.0, 'TOEFL_Score': 113.0, 'IELTS_Score': 8.5, 'CGPA': 2.23, 'University_Rating': 1, 'SOP': 3.0, 'LOR': 2.0, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 10, 'Internship': 'No', 'Leadership_Score': 4, 'Awards_Count': 0, 'Country': 'India', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2024, 'Scholarship_Awarded': 'No'}
47 : {'_id': ObjectId('6a5c93656eed02b82b98195b'), 'GRE_Score': 324.0, 'TOEFL_Score': 96.0, 'IELTS_Score': 7.5, 'CGPA': 3.3, 'University_Rating': 5, 'SOP': 4.8, 'LOR': 1.9, 'Research': 0, 'Publications': 0, 'Work_Experience_Months': 23, 'Internship': 'Yes', 'Leadership_Score': 5, 'Awards_Count': 0, 'Country': 'Bangladesh', 'Target_Program': 'EMJM Cyber', 'Graduation_Year': 2025, 'Scholarship_Awarded': 'No'}
48 : {'_id': ObjectId('6a5c93656eed02b82b98195c'), 'GRE_Score': 297.0, 'TOEFL_Score': 107.0, 'IELTS_Score': 8.0, 'CGPA': 3.84, 'University_Rating': 2, 'SOP': 3.0, 'LOR': 4.3, 'Research': 0, 'Publications': 2, 'Work_Experience_Months': 15, 'Internship': 'Yes', 'Leadership_Score': 6, 'Awards_Count': 1, 'Country': 'India', 'Target_Program': 'EMJM DS', 'Graduation_Year': 2022, 'Scholarship_Awarded': 'No'}

In [22]:
df = pd.DataFrame(list(collection.find()))

In [23]:
df.head()

,_id,GRE_Score,TOEFL_Score,IELTS_Score,CGPA,University_Rating,SOP,LOR,Research,Publications,Work_Experience_Months,Internship,Leadership_Score,Awards_Count,Country,Target_Program,Graduation_Year,Scholarship_Awarded
0,6a5c93656eed02b82b98192c,295.0,96.0,7.5,2.93,2,4.9,1.7,0,1,8,No,5,0,Nepal,EMJM Cyber,2024,No
1,6a5c93656eed02b82b98192d,340.0,119.0,9.0,3.76,3,4.1,1.7,0,1,31,Yes,4,0,Pakistan,EMJM Cyber,2025,No
2,6a5c93656eed02b82b98192e,336.0,96.0,7.5,3.12,1,3.2,1.8,1,2,29,Yes,4,1,Bangladesh,EMJM Cyber,2022,No
3,6a5c93656eed02b82b98192f,337.0,108.0,8.0,2.11,4,3.4,1.3,0,0,35,Yes,3,0,Bangladesh,EMJM DS,2025,No
4,6a5c93656eed02b82b981930,323.0,98.0,7.5,3.40,1,1.1,1.3,0,1,16,Yes,2,0,India,EMJM DS,2025,No

In [25]:
if "_id" in df.columns.to_list():
    df.drop(columns=["_id"], inplace=True)

In [26]:
df.head()

,GRE_Score,TOEFL_Score,IELTS_Score,CGPA,University_Rating,SOP,LOR,Research,Publications,Work_Experience_Months,Internship,Leadership_Score,Awards_Count,Country,Target_Program,Graduation_Year,Scholarship_Awarded
0,295.0,96.0,7.5,2.93,2,4.9,1.7,0,1,8,No,5,0,Nepal,EMJM Cyber,2024,No
1,340.0,119.0,9.0,3.76,3,4.1,1.7,0,1,31,Yes,4,0,Pakistan,EMJM Cyber,2025,No
2,336.0,96.0,7.5,3.12,1,3.2,1.8,1,2,29,Yes,4,1,Bangladesh,EMJM Cyber,2022,No
3,337.0,108.0,8.0,2.11,4,3.4,1.3,0,0,35,Yes,3,0,Bangladesh,EMJM DS,2025,No
4,323.0,98.0,7.5,3.40,1,1.1,1.3,0,1,16,Yes,2,0,India,EMJM DS,2025,No